Pract01:task4 | Radoslav Peev
GeorgiTerziev02/Object-oriented_programming_FMI pull request #33
Opened 2023-03-17 19:18 UTC by Radopeev

Radoslav Peev
SI 3 7MI0600261

2023-03-19 11:03 UTC, YavorAlexandrov requested changes

2023-03-19 11:03 UTC, YavorAlexandrov commented on task4.cpp
> +        source++;
what if source's size is bigger than destination's capacity?

2023-03-19 11:03 UTC, YavorAlexandrov commented on task4.cpp
> +    ptr=destination;
why do you need this?

2023-03-19 11:03 UTC, YavorAlexandrov commented on task4.cpp
> +    char* getTask(const char* pwd) {
get methods always return constant views of the objects. In this case it is necessary to return a const char* so the array is immutable.

2023-03-19 11:03 UTC, YavorAlexandrov commented on task4.cpp
> +    char* getTask(const char* pwd) {
methods that don't change the state of the current object must be annotated with const after the method signature

2023-03-19 11:03 UTC, YavorAlexandrov commented on task4.cpp
> +    int getLoginFail() {
this method is also const

2023-03-26 14:45 UTC, GeorgiTerziev02 requested changes

2023-03-26 14:45 UTC, GeorgiTerziev02 commented on task4.cpp
> +        this->failedLogins++;
else failedlogins++

2023-03-26 14:45 UTC, GeorgiTerziev02 commented
View the uploaded solution

2023-03-26 14:45 UTC, closed without merging