Pract.04: Add 02 | Tsvetelina Mancheva
GeorgiTerziev02/Object-oriented_programming_FMI pull request #34
Opened 2023-03-22 14:29 UTC by manchevatsveti

#Tsvetelina Mancheva
SI 3 0MI0600239

2023-03-22 17:30 UTC, YavorAlexandrov requested changes

2023-03-22 17:30 UTC, YavorAlexandrov commented on Sem. 04/Pract. 04/Task02.cpp
> +		this->name = new char[nameLen+1];
memory leak. What if we call setNameFromFile multiple times?

2023-03-22 17:30 UTC, YavorAlexandrov commented on Sem. 04/Pract. 04/Task02.cpp
> +		this->description = new char[descriptionLen + 1];
memory leak

2023-03-22 17:30 UTC, YavorAlexandrov commented on Sem. 04/Pract. 04/Task02.cpp
> +		ifs.read(this->name, descriptionLen);
This causes the heap corruption. You are populating the wrong array. this->name has length less than this->description and when you read the description in the name array it overflows hence heap corruption

2023-03-22 17:30 UTC, YavorAlexandrov commented on Sem. 04/Pract. 04/Task02.cpp
> +	void setDescriptionFromFile(std::ifstream& ifs, unsigned descriptionLen) {
this is basically the same function as setNameFromFile().Avoid code duplication

2023-03-22 17:30 UTC, YavorAlexandrov commented on Sem. 04/Pract. 04/Task02.cpp
> +	void setPoints(unsigned points) {
setter methods are a good place to validate input

2023-03-22 17:30 UTC, YavorAlexandrov commented on Sem. 04/Pract. 04/Task02.cpp
> +	Exam() {
this can be rewritten as `Exam() = default;`

2023-03-30 18:41 UTC, YavorAlexandrov requested changes

2023-03-30 18:41 UTC, YavorAlexandrov commented on Sem. 04/Pract. 04/Task.h
> +	void print();
function should be const

2023-03-30 18:41 UTC, YavorAlexandrov commented on Sem. 04/Pract. 04/Task.cpp
> +	points = 0;
default values are already set in the class definition

2023-03-30 18:41 UTC, YavorAlexandrov commented on Sem. 04/Pract. 04/Task.cpp
> +	this->description[nameLen] = '\0';
strcpy already sets this

2023-03-30 18:41 UTC, YavorAlexandrov commented on Sem. 04/Pract. 04/Task.cpp
> +	for (int i = 0; i < nameLen; i++) {
simply print it as `std::cout<<name;`

2023-03-30 18:41 UTC, YavorAlexandrov commented on Sem. 04/Pract. 04/Task.cpp
> +	for (int i = 0; i < desLen; i++) {
`std::cout<<description;`

2023-03-30 18:41 UTC, YavorAlexandrov commented on Sem. 04/Pract. 04/Exam.h
> +	unsigned getMax();
function should be const

2023-03-30 18:41 UTC, YavorAlexandrov commented on Sem. 04/Pract. 04/Exam.cpp
> +	this->minPoints = minPoints;
validate minPoints

2023-03-30 18:41 UTC, YavorAlexandrov commented on Sem. 04/Pract. 04/Exam.cpp
> +void Exam::setPoints(unsigned minPoints) {
this is the same function as changeMin()

2023-03-30 18:41 UTC, YavorAlexandrov commented on Sem. 04/Pract. 04/Exam.h
> +	void print();
function should be const

2023-05-19 10:58 UTC, GeorgiTerziev02 commented
Due to inactivity

2023-05-19 10:58 UTC, closed without merging