Pract.08: Add 01 | Asen Krasimirov
GeorgiTerziev02/Object-oriented_programming_FMI pull request #40
Opened 2023-04-13 14:49 UTC by asen-krasimirov

Asen Krasimirov 
SI 3 2MI0600231

2023-04-16 20:50 UTC, nikola354 reviewed
Good solution. Did not see how to edit a grade?
`Записана оценка за дадено задание може да се променя, но не може да се изтрива!`

2023-04-16 20:50 UTC, nikola354 commented on prac8 solutions/Student/Student.h
> +    ~Student();
you don't need to implement the rule of 4 since you don't have dynamic memory in this class (class Name handles its own dynamic memory)

2023-04-16 20:50 UTC, nikola354 commented on prac8 solutions/Grade/Grade.h
> +    ~Grade();
same as in Student

2023-04-16 20:50 UTC, nikola354 commented on prac8 solutions/OOPCourse/OOPCourse.cpp
> +    _grades[_gradesCount++] = new Grade(assignmentName, teacherName, studentFac, grade);
`Всеки студент трябва да има най-много една оценка за дадено задание.`
Това проверяваш ли го някъде?

2023-04-17 14:29 UTC, GeorgiTerziev02 commented on prac8 solutions/Student/Student.h
> +    ~Student();
You can just use a string instead of the name class

2023-04-17 14:37 UTC, asen-krasimirov commented on prac8 solutions/OOPCourse/OOPCourse.cpp
> +    _grades[_gradesCount++] = new Grade(assignmentName, teacherName, studentFac, grade);
Вече да, пропуснал съм ги тези условия

2023-04-17 15:53 UTC, nikola354 requested changes

2023-04-17 15:53 UTC, nikola354 commented on prac8 solutions/OOPCourse/OOPCourse.h
> +    Grade &getGrade(unsigned studentFac, const char *assignmentName, const char *teacherName);
make getGrade to return const Grade &, then you can make both methods constant

2023-04-17 19:18 UTC, asen-krasimirov commented on prac8 solutions/OOPCourse/OOPCourse.h
> +    Grade &getGrade(unsigned studentFac, const char *assignmentName, const char *teacherName);
okey, but I use getGrade in changeGrade, so I have to overload getGrade to work with const as well

2023-04-19 13:29 UTC, nikola354 approved these changes

2023-05-19 11:00 UTC, merged