Pract.08 : Add 01 | Kristina Ganova
GeorgiTerziev02/Object-oriented_programming_FMI pull request #41
Opened 2023-04-13 22:54 UTC by kristinaganova

2023-04-13 22:56 UTC, kristinaganova commented
Kristina Ganova
SI 3 9MI0600147

2023-04-16 12:04 UTC, GeorgiTerziev02 requested changes

2023-04-16 12:04 UTC, GeorgiTerziev02 commented on Sem. 08/OOP Course/Teacher/Teacher.h
> +    MyString getTeacherName() const;
return const ref

2023-04-16 12:04 UTC, GeorgiTerziev02 commented on Sem. 08/OOP Course/Teacher/Teacher.cpp
> +}
use member initializer list, so that you can use the copy construcotr

2023-04-16 12:04 UTC, GeorgiTerziev02 commented on Sem. 08/OOP Course/Student/Student.h
> +	MyString getName() const ;
const ref

2023-04-16 12:04 UTC, GeorgiTerziev02 commented on Sem. 08/OOP Course/Student/Student.h
> +	Grade getGrade(unsigned int index) const;
const ref

2023-04-16 12:04 UTC, GeorgiTerziev02 commented on Sem. 08/OOP Course/Student/Student.h
> +	void setGrades(const Grade* grades);
you should pass the count of the grades as well

2023-04-16 12:04 UTC, GeorgiTerziev02 commented on Sem. 08/OOP Course/Student/Student.h
> +	double averageGrade;
memory alignment!

2023-04-16 12:04 UTC, GeorgiTerziev02 commented on Sem. 08/OOP Course/Student/Student.cpp
> +	}
The static array of grades have already been initialized with default constructor for each index

2023-04-16 12:04 UTC, GeorgiTerziev02 commented on Sem. 08/OOP Course/OOPcource/OOPcource.h
> +
copy constructor, operator=?

2023-04-16 12:04 UTC, GeorgiTerziev02 commented on Sem. 08/OOP Course/MyString/helpers.cpp
> +#include "helpers.h"
You can use these functions from cstring

2023-04-16 12:04 UTC, GeorgiTerziev02 commented on Sem. 08/OOP Course/MyString/helpers.h
> +#pragma once
use <cstring>

2023-04-16 12:04 UTC, GeorgiTerziev02 commented on Sem. 08/OOP Course/MyString/MyString.cpp
> +	data[len] = '\0';
strcpy

2023-04-16 12:04 UTC, GeorgiTerziev02 commented on Sem. 08/OOP Course/MyString/MyString.cpp
> +MyString::MyString(const char* str, size_t len) : len(len), data(new char[len + 1])
Tip: allocate the new char array inside the body of the consturctor, is more readable that way

2023-04-16 12:04 UTC, GeorgiTerziev02 commented on Sem. 08/OOP Course/Grade/Grade.h
> +	Teacher teacher;
Teacher should be a pointer or reference, because you want to refer to a teacher from the oop course, you do not want to create a copy of a teacher for every grade

2023-04-16 12:04 UTC, GeorgiTerziev02 commented on Sem. 08/OOP Course/Grade/Grade.h
> +	MyString getSubject() const;
return const ref

2023-04-16 12:04 UTC, GeorgiTerziev02 commented on Sem. 08/OOP Course/OOPcource/OOPcource.cpp
> +	this->assistants[0] = Teacher(assistant);
use member initializer list

2023-04-16 12:04 UTC, GeorgiTerziev02 commented on Sem. 08/OOP Course/OOPcource/OOPcource.cpp
> +	}
You can create a function that return -1 if the user is not found otherwise it will return the index of the student.
This function can be used here and in the other functions where you are searching for a student to do a specific operation

2023-05-19 11:27 UTC, GeorgiTerziev02 commented
Solution have already been merged

2023-05-19 11:27 UTC, closed without merging