Pract.08: Add 01 | Stefan Shivarov
GeorgiTerziev02/Object-oriented_programming_FMI pull request #43
Opened 2023-04-17 20:12 UTC by StefanShivarov

Stefan Shivarov
SI 3 9MI0600175

2023-04-18 16:15 UTC, nikola354 requested changes
Very good solution. Did not see how to edit a grade:
`Записана оценка за дадено задание може да се променя, но не може да се изтрива!`

2023-04-18 16:15 UTC, nikola354 commented on Sem. 08/Pract. 08/Task 01/Course.h
> +	Teacher assistants[MAX_ASSISTANTS_AMOUNT];
Since class Teacher has only one property, you can just use char *

2023-04-19 13:25 UTC, StefanShivarov commented
I added edit grade functionality.

2023-04-19 13:46 UTC, nikola354 approved these changes

2023-04-19 14:38 UTC, merged