Pract1 all exercises
GeorgiTerziev02/Object-oriented_programming_FMI pull request #68
Opened 2024-03-04 21:44 UTC by VladiCI04

Pract1 all exercises

2024-03-05 22:06 UTC, khatoni requested changes

2024-03-05 22:06 UTC, khatoni commented on Vladimir Ivanov SI/Pract1.2/Pract1.2.cpp
> +}
Just use the operator +, there is no need to write your own function.

2024-03-05 22:06 UTC, khatoni commented on Vladimir Ivanov SI/Pract1.2/Pract1.2.cpp
> +ComplexNum& findSum(const ComplexNum& num1, const ComplexNum& num2) {
Big mistake. The return type should not be ComplexNum&, because you create local variable result, which will die after the function scope.

2024-03-05 22:06 UTC, khatoni commented on Vladimir Ivanov SI/Pract1.3/Pract1.3.cpp
> +    double sum = p.x + p.y;
p.x^2 + p.y^2

2024-03-05 22:06 UTC, khatoni commented on Vladimir Ivanov SI/Pract1.4/Pract1.4.cpp
> +    for (unsigned int i = 0; i < studentsCount; i++) {
Better use size_t

2024-03-05 22:06 UTC, khatoni commented on Vladimir Ivanov SI/Pract1.4/Pract1.4.cpp
> +        groupAverageGrade += students->grade;
Not a good idea to use here groupAverageGrade, because the name is misleading. Also, do you mean students[i].grade;

2024-03-05 22:06 UTC, khatoni commented on Vladimir Ivanov SI/Pract1.4/Pract1.4.cpp
> +void sortStudents(const unsigned int studentsCount, Student*& sortedStudents) {
Bubble sort is not the best option here.
No need of &

2024-03-05 22:06 UTC, khatoni commented on Vladimir Ivanov SI/Pract1.4/Pract1.4.cpp
> +void printStudents(Student*& students, const unsigned int studentsCount) {
add const
No need to use &

2024-03-05 22:06 UTC, khatoni commented on Vladimir Ivanov SI/Pract1.4/Pract1.4.cpp
> +        if (*students[i].fn == *fn) {
Do not compare char arrays like this.

2024-03-05 22:06 UTC, khatoni commented on Vladimir Ivanov SI/Pract1.4/Pract1.4.cpp
> +void readStudents(const unsigned int studentsCount, Student*& students) {
You can use only Student*

2024-03-05 22:06 UTC, khatoni commented on Vladimir Ivanov SI/Pract1.5/Pract1.5.cpp
> +		if (str[i] < 0 || str[i] > 9) {
Use '0', '9'

2024-03-05 22:06 UTC, khatoni commented on Vladimir Ivanov SI/Pract1.6/Pract1.6.cpp
> +    deleteMatrix(transponateMatrix, rows);
Memory leak- the initial matrix elements.

2024-03-05 22:06 UTC, khatoni commented on Vladimir Ivanov SI/Pract1.6/Pract1.6.cpp
> +void printMatrix(int** matrix, const unsigned int rows, const unsigned int cols) {
To follow const correctness - use const int* const* matrix.

2024-03-05 22:06 UTC, khatoni commented on Vladimir Ivanov SI/Pract1/Pract1.cpp
> +    Person personRef = p;
Person* personRef = &p;
cout<<p->age;

2024-03-06 07:31 UTC, GeorgiTerziev02 reviewed
Do not create a folder with your name in the repo. Upload the solutions inside the pract folder.
Also, please do not create a folder for every file.

2024-03-06 07:31 UTC, GeorgiTerziev02 commented on Vladimir Ivanov SI/Pract1.3/Pract1.3.cpp
> +    double sum = p.x + p.y;
later there is no need of abs

2024-03-06 07:31 UTC, GeorgiTerziev02 commented on Vladimir Ivanov SI/Pract1.3/Pract1.3.cpp
> +    return squareNum;
one liner, better create pow func

2024-03-06 07:31 UTC, GeorgiTerziev02 commented on Vladimir Ivanov SI/Pract1.3/Pract1.3.cpp
> +    return distance;
one liner

2024-03-06 07:31 UTC, GeorgiTerziev02 commented on Vladimir Ivanov SI/Pract1.3/Pract1.3.cpp
> +    if (p.x > 0) {
This whole thing should be one function

2024-03-06 07:31 UTC, GeorgiTerziev02 commented on Vladimir Ivanov SI/Pract1.3/Pract1.3.cpp
> +    else if (abs(p.x) == radius || abs(p.y) <= radius) {
this is not the way we compare doubles

2024-03-06 07:31 UTC, GeorgiTerziev02 commented on Vladimir Ivanov SI/Pract1.6/Pract1.6.cpp
> +void deleteMatrix(int** matrix, const unsigned int rows) {
use uint or type def it
unsigned int is too long and only polutes the code

2024-03-06 07:31 UTC, GeorgiTerziev02 commented on Vladimir Ivanov SI/Pract1.5/Pract1.5.cpp
> +		if ((str[i] >= 'a' && str[i] <= 'z') || (str[i] >= 'A' && str[i] <= 'Z')) {
Create function

2024-03-06 07:31 UTC, GeorgiTerziev02 commented on Vladimir Ivanov SI/Pract1.5/Pract1.5.cpp
> +		if (str[i] < 0 || str[i] > 9) {
and function

2024-03-06 07:31 UTC, GeorgiTerziev02 commented on Vladimir Ivanov SI/Pract1.4/Pract1.4.cpp
> +}
This is not a very abstract swap function, you need to pass the two positions that will be swapped

2024-03-06 07:32 UTC, GeorgiTerziev02 requested changes
.

2024-03-21 16:34 UTC, GeorgiTerziev02 commented
Closed due to inactivity

2024-03-21 16:34 UTC, closed without merging