Pract. 06: Add 00-03 | Rami Hennawi
GeorgiTerziev02/Object-oriented_programming_FMI pull request #72
Opened 2024-04-03 17:10 UTC by RamiHennawi

2024-04-05 06:52 UTC, khatoni requested changes
Multiset is not memory efficient

2024-04-05 06:52 UTC, khatoni commented on Practicum/Pract. Rami/pract 06/02/NumberSeries/NumberSeries.cpp
> +	free();
bug, initial value set to 0 in free()

2024-04-05 06:52 UTC, khatoni commented on Practicum/Pract. Rami/pract 06/02/NumberSeries/NumberSeries.cpp
> +	transitionFunction = newFunction;
free() missing if I already have generated some numbers with previous function.

2024-04-05 06:52 UTC, khatoni commented on Practicum/Pract. Rami/pract 06/03/MultiSet/MultiSet.h
> +	int* elements = nullptr;
why int

2024-04-21 16:11 UTC, GeorgiTerziev02 commented
Closed due to inactivity

2024-04-21 16:11 UTC, closed without merging